Feature/ubi 342 friendslist v1
Ubivius/microservice-friendslist pull request #2
Opened 2021-03-18 20:44 UTC by MaximeStOnge

#### What changes does this PR contain?
First iteration of friendslist

#### Which JIRA ticket ID's are associated with this PR?
UBI-342

#### Does this PR change the outward facing API?
yes

#### Additional comments and information

@ubivius/microservices

2021-03-18 21:39 UTC, ArcticWalrus requested changes

2021-03-18 21:39 UTC, ArcticWalrus commented on pkg/data/relationships.go
> +    None RelationshipType = iota  // user has no intrinsic relationship
Alignment is weird here

2021-03-18 21:39 UTC, ArcticWalrus commented on pkg/data/relationships.go
> +// Formatting done with json tags to the right. "-" : don't include when encoding to json
remove comment on json tags
Also alignment is weird again

2021-03-18 21:39 UTC, ArcticWalrus commented on pkg/data/relationships.go
> +		}else if relationship.User2.UserID == id && relationship.User2.RelationshipType == PendingIncoming{
space before else

2021-03-18 21:39 UTC, ArcticWalrus commented on pkg/data/validate.go
> +// ValidateRelationship a relationship with json validation and customer SKU validator
Customer sku?

2021-03-18 21:42 UTC, ArcticWalrus commented
relationshiptype should probably be a string. When I do the curls I have no idea what the data means

2021-03-18 21:45 UTC, ArcticWalrus requested changes

2021-03-18 21:45 UTC, ArcticWalrus commented on pkg/data/relationships.go
> +// Formatting done with json tags to the right. "-" : don't include when encoding to json
Make the json value user_1 and user_2
conversation_id

2021-03-18 21:45 UTC, ArcticWalrus commented on pkg/data/relationships.go
> +	UserID      		int  	     		`json:"userid" validate:"required"`
in json user_id
relationship_type
Unreadable otherwise in json strings

2021-03-18 21:45 UTC, ArcticWalrus commented on README.md
> -# microservice-template
Add description of the endpoints in readme. I'm not sure what each endpoint does just from reading the urls

2021-03-20 19:08 UTC, ArcticWalrus approved these changes

2021-03-21 14:29 UTC, JeremiSavard approved these changes

2021-03-21 14:29 UTC, merged